title: David Martinez's Homepage
page-top-title: David Martinez
top-section-bg-text: Hi, welcome to my website!
home-subtitle: David Martinez&ensp;|&ensp;AI & Robotics Engineer
copyright-text: '&copy; David Martinez 2024-2025. All Rights Reserved.'
