title: David Martinez's Homepage
page-top-title: David Martinez
top-section-bg-text: Computer Science
home-subtitle: David Martinez&ensp;|&ensp;李森
copyright-text: '&copy; David Martinez 2023-2024. All Rights Reserved.'
